# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XwiLZhLoHoN205ndIQE3NMYguamdqye4
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import random
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

!unzip -q "/content/archive.zip" -d "/content/veriseti/"

dataset_path = "/content/veriseti/data" # Yeni veri setine göre güncellendi

try:
    classes = os.listdir(dataset_path)
    num_classes = len(classes)
    print(f"Bulunan Sınıflar: {classes}")
    print(f"Toplam Sınıf Sayısı: {num_classes}")
except FileNotFoundError:
    print(f"HATA: '{dataset_path}' klasörü bulunamadı. Lütfen yolu kontrol edin.")
    num_classes = 4 # cloudy, desert, green_area, water

def get_data_generators(dataset_path, batch_size):
    """
    Verilen batch_size değerine göre eğitim ve validasyon veri yükleyicilerini oluşturur.
    GA'nın her bireyi farklı bir batch_size seçebileceği için bu işlemi dinamik hale getirdik.
    """
    datagen = ImageDataGenerator(rescale=1.0/255, validation_split=0.2)

    train_generator = datagen.flow_from_directory(
        dataset_path,
        target_size=(64, 64), # GA sürecini hızlandırmak için 64x64 yapıldı
        batch_size=batch_size,
        class_mode="categorical",
        subset='training',
        shuffle=True
    )

    validation_generator = datagen.flow_from_directory(
        dataset_path,
        target_size=(64, 64), # GA sürecini hızlandırmak için 64x64 yapıldı
        batch_size=batch_size,
        class_mode="categorical",
        subset='validation',
        shuffle=False
    )

    return train_generator, validation_generator

def build_and_train_model(params, dataset_path, num_classes, verbose=0):
    """
    Verilen hiperparametre sözlüğüne göre modeli kurar, eğitir ve history objesini döndürür.
    Hem Basic CNN hem de GA içindeki fitness fonksiyonu için kullanılacak.
    """
    train_generator, validation_generator = get_data_generators(dataset_path, params["batch_size"])

    model = Sequential()
    # input_shape target_size ile uyumlu olarak 64,64,3 yapıldı
    model.add(Conv2D(32, (3,3), activation=params["activation"], input_shape=(64,64,3)))
    model.add(MaxPooling2D(2,2))

    model.add(Conv2D(64, (3,3), activation=params["activation"]))
    model.add(MaxPooling2D(2,2))

    model.add(Flatten())

    model.add(Dense(params["dense_neurons"], activation=params["activation"]))
    model.add(Dropout(params["dropout"]))

    model.add(Dense(num_classes, activation='softmax'))

    # Optimizer ayarı
    if params["optimizer"] == "adam":
        optimizer = tf.keras.optimizers.Adam(learning_rate=params["learning_rate"])
    else:
        optimizer = tf.keras.optimizers.RMSprop(learning_rate=params["learning_rate"])

    model.compile(
        optimizer=optimizer,
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    history = model.fit(
        train_generator,
        validation_data=validation_generator,
        epochs=params["epochs"],
        verbose=verbose
    )

    return model, history

hyperparameter_space = {
    "learning_rate":[0.1,0.01,0.001],
    "batch_size" : [8,16,32],
    "optimizer" : ["adam","rmsprop"],
    "dropout" : [0.3,0.5],
    "dense_neurons": [64,128,256],
    "activation":["relu","tanh"],
    "epochs": [5,10]
}

def create_individual():
    individual = {
        "learning_rate": random.choice(hyperparameter_space["learning_rate"]),
        "batch_size": random.choice(hyperparameter_space["batch_size"]),
        "optimizer": random.choice(hyperparameter_space["optimizer"]),
        "dropout": random.choice(hyperparameter_space["dropout"]),
        "dense_neurons": random.choice(hyperparameter_space["dense_neurons"]),
        "activation": random.choice(hyperparameter_space["activation"]),
        "epochs": random.choice(hyperparameter_space["epochs"])
    }
    return individual

def fitness_function(individual, dataset_path, num_classes):
    _, history = build_and_train_model(individual, dataset_path, num_classes, verbose=0)
    val_accuracy = max(history.history['val_accuracy'])
    return val_accuracy

def selection(population, fitness_scores):
    sorted_indices = np.argsort(fitness_scores)[::-1]
    selected = [population[i] for i in sorted_indices[:2]]
    return selected

def crossover(parent1, parent2):
    child = {}
    for key in parent1.keys():
        child[key] = random.choice([parent1[key], parent2[key]])
    return child

def mutation(individual, mutation_rate=0.2):
    if random.random() < mutation_rate:
        key = random.choice(list(individual.keys()))
        individual[key] = random.choice(hyperparameter_space[key])
    return individual

def next_generation(selected, population_size, elitism_count=1):
    new_population = selected[:elitism_count].copy()
    while len(new_population) < population_size:
        p1, p2 = random.sample(selected, 2)
        child = crossover(p1, p2)
        child = mutation(child)
        new_population.append(child)
    return new_population

if __name__ == "__main__":

    #BASIC (BASELINE) CNN EĞİTİMİ ---

    print("ADIM 1: BASIC (BASELINE) CNN EĞİTİLİYOR...")


    basic_params = {
        "learning_rate": 0.001,
        "batch_size": 32,
        "optimizer": "adam",
        "dropout": 0.5,
        "dense_neurons": 128,
        "activation": "relu",
        "epochs": 10
    }

    basic_model, basic_history = build_and_train_model(basic_params, dataset_path, num_classes, verbose=1)
    basic_best_val_acc = max(basic_history.history['val_accuracy'])
    print(f"\n[Basic CNN] En İyi Validation Accuracy: {basic_best_val_acc:.4f}")

#GENETİK ALGORİTMA İLE OPTİMİZASYON ---
print("ADIM 2: GENETİK ALGORİTMA BAŞLIYOR...")
num_generations = 5
population_size = 5
best_fitness_history = []

population = [create_individual() for _ in range(population_size)]

for generation in range(num_generations):
    print(f"\n--- Jenerasyon {generation + 1}/{num_generations} ---")

    fitness_scores = []
    for i, individual in enumerate(population):
        score = fitness_function(individual, dataset_path, num_classes)
        fitness_scores.append(score)
        print(f"Birey {i+1} Val Acc: {score:.4f} | Parametreler: {individual}")

    best_idx = np.argmax(fitness_scores)
    best_score = fitness_scores[best_idx]
    best_fitness_history.append(best_score)
    print(f">> Bu Jenerasyonun En İyi Skoru: {best_score:.4f}")

    if generation == num_generations - 1:
        break

    selected_individuals = selection(population, fitness_scores)
    population = next_generation(selected_individuals, population_size, elitism_count=1)
best_ga_params = population[np.argmax(fitness_scores)]

# --- ADIM C: OPTİMİZE EDİLMİŞ (GA) CNN EĞİTİMİ ---

print("ADIM 3: EN İYİ HİPERPARAMETRELERLE GA CNN EĞİTİLİYOR...")

print(f"Kullanılan Parametreler: {best_ga_params}")

ga_model, ga_history = build_and_train_model(best_ga_params, dataset_path, num_classes, verbose=1)
ga_best_val_acc = max(ga_history.history['val_accuracy'])


    # --- SONUÇLARIN ÖZETİ ---

print("KARŞILAŞTIRMA SONUÇLARI")

print(f"Basic CNN Validation Accuracy: {basic_best_val_acc:.4f}")
print(f"GA CNN Validation Accuracy:    {ga_best_val_acc:.4f}")

if ga_best_val_acc > basic_best_val_acc:
    print(f"-> Harika! Genetik Algoritma modeli {ga_best_val_acc - basic_best_val_acc:.4f} oranında daha başarılı.")
else:
    print("-> Temel model daha iyi veya aynı performansı gösterdi. Hiperparametre arama uzayını veya jenerasyon sayısını artırabilirsiniz.")

plt.figure(figsize=(15, 5))

plt.subplot(1, 3, 1)
plt.plot(range(1, num_generations + 1), best_fitness_history, marker='o', color='b', linewidth=2)
plt.title('GA Yakınsama (Fitness) Grafiği')
plt.xlabel('Jenerasyon')
plt.ylabel('En İyi Validation Accuracy')
plt.xticks(range(1, num_generations + 1))
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 3, 2)
plt.plot(basic_history.history['val_accuracy'], label='Basic CNN Val Acc', linestyle='--', color='red', marker='x')
plt.plot(ga_history.history['val_accuracy'], label='GA CNN Val Acc', color='green', marker='o')
plt.title('Validation Accuracy Karşılaştırması')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(1, 3, 3)
plt.plot(basic_history.history['val_loss'], label='Basic CNN Val Loss', linestyle='--', color='red', marker='x')
plt.plot(ga_history.history['val_loss'], label='GA CNN Val Loss', color='green', marker='o')
plt.title('Validation Loss Karşılaştırması')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)

plt.subplot(2, 2, 4)
plt.plot(range(1, num_generations + 1), best_fitness_history, marker='s', color='darkblue', linewidth=2, markersize=8)
plt.title('4. Fitness Değişim Grafiği (GA Jenerasyonları)')
plt.xlabel('Jenerasyon')
plt.ylabel('En İyi Fitness (Val Accuracy)')
plt.xticks(range(1, num_generations + 1))
plt.grid(True, linestyle='--', alpha=0.7)